### ISSUE TITLE
#create video TypeError: Required argument 'apiPreference' (pos 2) not found

### ISSUE THREAD

**Issue by gzhhhere** [genforce/mganprior#20]
Hi!
During video creating, i met a problem:
Traceback (most recent call last):
  File "./mganprior-master/multi_code_inversion.py", line 112, in <module> main(args)
  File "mganprior-master/multi_code_inversion.py", line 52, in main frameSize=(frameSize, frameSize))
TypeError: Required argument 'apiPreference' (pos 2) not found. 
How should i solve it?  
![image](https://user-images.githubusercontent.com/43848061/116238185-a67a5c00-a793-11eb-8402-51f2314675ba.png)

**Comment by gzhhhere** [comment]
it seems because i used 3.x python.
